version: '3.8'

services:
   basket.api:
    container_name: lde.basket.api
    build:
      context: .
      dockerfile: Basket/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - Authorization__Authority=http://www.figurineshop.com:5002
      - Redis__Host=www.figurineshop.com:6380
      - Redis__CacheTimeout=01:00:00
      - PathBase=http://www.figurineshop.com:5003
    depends_on:
      - redis
    ports:
      - 5003:5003
   catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: Catalog/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
       - ConnectionString=server=www.figurineshop.com;port=5433;database=catalog;uid=postgres;password=postgres;
       - Authorization__Authority=http://www.figurineshop.com:5002
       - PathBase=http://www.figurineshop.com:5000
    depends_on:
      - postgres
    ports:
      - 5000:5000
   comment.api:
    container_name: lde.comment.api
    build:
      context: .
      dockerfile: Comment/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5004
       - ConnectionString=server=www.figurineshop.com;port=5434;database=comment;uid=postgres;password=postgres;
       - Authorization__Authority=http://www.figurineshop.com:5002
       - PathBase=http://www.figurineshop.com:5004
    depends_on:
      - postgresComment
    ports:
      - 5004:5004
   web.mvc:
    container_name: lde.web.mvc
    build:
      context: .
      dockerfile: MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - MvcUrl=http://www.figurineshop.com:5001
      - BasketUrl=http://www.figurineshop.com:5003/api/v1/basketbff
      - CatalogUrl=http://www.figurineshop.com:5000/api/v1/catalogbff
      - Authorization__Authority=http://www.figurineshop.com:5002
      - IdentityUrl=http://www.figurineshop.com:5002
      - CallBackUrl=http://www.figurineshop.com/
      - RedirectUri=http://www.figurineshop.com/signin-oidc
    depends_on:
      - catalog.api
      - identityserver
    ports:
      - 5001:5001
   nginx:
    image: nginx
    container_name: lde.nginx
    ports:
      - 80:80
    volumes:
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./Proxy/assets:/var/www/assets
   postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
   postgresComment:
    image: postgres
    container_name: lde.postgresComment
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
   identityserver:
    container_name: lde.identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - MvcUrl=http://www.figurineshop.com
      - CatalogApi=http://www.figurineshop.com:5000
      - BasketApi=http://www.figurineshop.com:5003
      - CommentApi=http://www.figurineshop.com:5004
    ports:
      - 5002:5002
   redis:
    image: redis
    container_name: lde.redis
    ports:
      - 6380:6379
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1